name: deploy

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/http-request-action
      - name: Deploy Request
        id: DeployRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://passport.lct24.dev.40ants.com/'
          method: 'POST'
          data: |
            {
              "jsonrpc": "2.0",
              "method": "deploy",
              "params": {"token": "${{ secrets.DEPLOY_TOKEN }}"},
              "id": 0
            }

      - name: Show Response
        run: |
          echo Response:
          echo ${{ steps.DeployRequest.outputs.response }}
          echo Headers:
          echo ${{ steps.DeployRequest.outputs.headers }}
          echo Status:
          echo ${{ steps.DeployRequest.outputs.status }}
